### ISSUE TITLE
Erro ao montar equação da reta.

### ISSUE THREAD

**Issue by crazyfrog22** [leandrocl2005/geometria-analitica-aplicada-exemplos#1]
Boa tarde, segui as instruções do seu código. Fiz com meu próprio dataset ".arff".

-Seguiu tudo como previsto, isolei 2 colunas numéricas e 1 categórica. Não irei mostrar o dataset que utilizei para evitar plágios, mas meu código ficou assim:

Filtros:
`dados = dados[['MINOR_AXIS', 'MAJOR_AXIS', 'CLASS']]`
`dados = dados[dados['CLASS'].isin([b"Arborio", b"Ipsala"])]`
Gráfico:
```
sns.scatterplot(
    data=dados, 
    x="MINOR_AXIS", 


    y="MAJOR_AXIS", 
    hue="CLASS")
plt.show()
```
Quando fui montar o coeficiente com este código
```
model = LinearSVC()
model.fit(dados.drop('CLASS', axis=1), dados['CLASS'])

a, b = model.coef_[0]
d = model.intercept_[0]

print('a:', a)
print('b:', b)
print('d:', d)
```
Apareceu o seguinte erro:
`You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead - the MultiLabelBinarizer transformer can convert to this format.`

Já tentei usar o  MultiLabelBinarizer para converter os dados com os seguintes códigos (entretanto continuo com o mesmo erro):
```
X = dados.drop('CLASS', axis=1)
y = dados['CLASS']
```
```
mb = MultiLabelBinarizer()
mb.fit(y)
mb.transform(y)
```
```
model = LinearSVC()
model.fit(X,y)
```

Meu gráfico com o scatterplot:

![download (d1)](https://user-images.githubusercontent.com/111524841/185447732-4dc358b1-5612-4c16-804e-b4d124c8bf4c.png)

Já procurei por diversos fórums no StackOverflow e outros repositórios, entretanto não obtive êxito. Há alguma maneira do senhor me auxiliar neste problema?

**Comment by leandrocl2005** [comment]
Tente fazer seu dataset em _.csv_


No começo desse tutorial tem explicando como montar um:

https://leandrocruvinel.medium.com/transformando-dados-com-python-e-pandas-parte-1-3eeccf52eece

**Comment by crazyfrog22** [comment]
> 

Muito obrigado. Tenha uma boa tarde!
